name: Self Hosted Runner

on:
  # Trigger the workflow on push on the main branch
  push:
    branches:
      - main
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      # - '.**'

permissions:
      id-token: write
      contents: read

jobs:
  setup_runner:
    name: Setup Runner
    runs-on: ubuntu-22.04
    outputs:
      runner_name: steps.create_github_runner.outputs.runner_name
    steps:
      - name: Create GitHub Runner 
        id: create_github_runner
        uses: pagopa/github-self-hosted-runner-azure-create-action@main
        with:
          client_id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          container_app_environment_name: "capp-env-pasq"
          resource_group_name: "pasquale-test"
          pat_token: ${{ secrets.BOT_TOKEN }}

  runner_job:
    name: Runner Job
    runs-on: [self-hosted, "${{ needs.setup_runner.outputs.runner_name }}" ]
    needs: setup_runner
    
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: 'Run CLI commands on self hosted runner'
        run: |
          echo "hello"
          pwd

  clear_runner:
    name: Clean Runner
    runs-on: ubuntu-22.04
    needs: [ setup_runner, runner_job]
    
    steps:

      - name: Login
        id: login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Delete GitHub Runner
        id: delete_github_runner
        run: |
          AZURE_RESORCE_GROUP_NAME="pasquale-test"
          AZURE_CONTAINER_APP_NAME=${{ needs.setup_runner.outputs.runner_name }}
          echo "[INFO] AZURE_CONTAINER_APP_NAME: ${AZURE_CONTAINER_APP_NAME}"

          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp delete \
            --name "${AZURE_CONTAINER_APP_NAME}" \
            --resource-group "${AZURE_RESORCE_GROUP_NAME}" \
            --yes

          echo "[INFO] AZURE_CONTAINER_APP_NAME deleted"

          sleep 30

          # sometimes delete operation needs more time to works,
          # so we retry the operation for 60 seconds

          START_TIME=$(date +%s)
          while [ $(( $(date +%s) - 60 )) -lt $START_TIME ]; do

            GITHUB_RUNNER_ID=$(curl \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.BOT_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/actions/runners | jq '.runners | map(select(.name | startswith("'${AZURE_CONTAINER_APP_NAME}'"))) | .[].id' -r)

            # [ -z "$GITHUB_RUNNER_ID" ] && echo "no runners found" && break
            if [ -z "$GITHUB_RUNNER_ID" ]
            then
              echo "[INFO] GITHUB_RUNNER_ID is empty"
              break
            fi

            echo "[INFO] GITHUB_RUNNER_ID: ${GITHUB_RUNNER_ID} is NOT empty"

            curl \
              -X DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.BOT_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/actions/runners/${GITHUB_RUNNER_ID}

            sleep 66

          done

          echo "[INFO] GITHUB_RUNNER_ID deleted"
