name: Release

on:
  # Trigger the workflow on push on the main branch
  push:
    branches:
      - main
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      # - '.**'

permissions:
      id-token: write
      contents: read

jobs:
  setup_runner:
    name: Setup Runner
    runs-on: ubuntu-22.04
    outputs:
      AZURE_CONTAINER_APP_NAME: ${{ steps.create_github_runner.outputs.AZURE_CONTAINER_APP_NAME }}
    
    steps:
      # - name: Checkout
      #   id: checkout
      #   uses: actions/checkout@v2
      #   with:
      #     persist-credentials: false
      #     fetch-depth: 0
      
      - name: Login
        id: login
        uses: azure/login@v1
        with:
          # ENVIRONMENT: prod
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: 'Run Azure CLI commands'
      #   run: |
      #     az account show
      #     az group list
      #     pwd

      - name: Create GitHub Runner
        id: create_github_runner
        run: |
          TIMESTAMP=$(date +%s)
          SELF_HOSTED_RUNNER_IMAGE="ghcr.io/pagopa/github-self-hosted-runner:v1.0.3"

          AZURE_RESORCE_GROUP_NAME="pasquale-test"
          AZURE_CONTAINER_APP_ENVIRONMENT_NAME="capp-env-pasq"
          AZURE_CONTAINER_APP_NAME="runner-${{ github.run_id }}${TIMESTAMP}"
          echo "[INFO] AZURE_CONTAINER_APP_NAME: ${AZURE_CONTAINER_APP_NAME}"
          echo "::set-output name=AZURE_CONTAINER_APP_NAME::${AZURE_CONTAINER_APP_NAME}"

          GITHUB_TOKEN=$(curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.BOT_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/runners/registration-token | jq ".token" -r)
            
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp create \
            --name "${AZURE_CONTAINER_APP_NAME}" \
            --resource-group "${AZURE_RESORCE_GROUP_NAME}" \
            --image "${SELF_HOSTED_RUNNER_IMAGE}" \
            --environment "${AZURE_CONTAINER_APP_ENVIRONMENT_NAME}" \
            --secrets github-token="${GITHUB_TOKEN}" \
            --env-vars \
            GITHUB_REPOSITORY="https://github.com/${{ github.repository }}" \
            GITHUB_TOKEN=secretref:github-token

      - name: Delete GitHub Runner
        id: delete_github_runner
        run: |
          AZURE_RESORCE_GROUP_NAME="pasquale-test"
          AZURE_CONTAINER_APP_NAME=${{ steps.create_github_runner.outputs.AZURE_CONTAINER_APP_NAME }}
          echo "[INFO] AZURE_CONTAINER_APP_NAME: ${AZURE_CONTAINER_APP_NAME}"

          az containerapp delete \
            --name "${AZURE_CONTAINER_APP_NAME}" \
            --resource-group "${AZURE_RESORCE_GROUP_NAME}" \
            --no-wait \
            --yes

          GITHUB_TOKEN=$(curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.BOT_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/runners/registration-token | jq ".token" -r)

          GITHUB_RUNNER_ID=$(curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            https://api.github.com/repos/${{ github.repository }}/actions/runners | jq '.runners | map(select(.name | startswith("'${AZURE_CONTAINER_APP_NAME}'"))) | .[].id' -r)

          echo "[INFO] GITHUB_RUNNER_ID: ${GITHUB_RUNNER_ID}"

          curl \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            https://api.github.com/repos/${{ github.repository }}/actions/runners/${GITHUB_RUNNER_ID}
